#!/usr/bin/env bash
#
# Shared iOS release-runner contract.
#
# The provisioning script and the release preflight source this file so a
# runner cannot be prepared with one toolchain or simulator contract and
# rejected by the workflow for another. Keep this file compatible with the
# bash 3.2 shipped by macOS.

IOS_RUNNER_PNPM_VERSION="10.26.1"
IOS_RUNNER_JAVA_MINIMUM_MAJOR="17"
IOS_RUNNER_SIMULATOR_NAME="iPhone SE (3rd generation)"
IOS_RUNNER_SIMULATOR_DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
IOS_RUNNER_REQUIRED_COMMANDS="xcrun pnpm java maestro"
IOS_RUNNER_CANDIDATE_APP_ID_ENVIRONMENT_VALUE="NATIVE_SMOKE_IOS_APP_ID"
IOS_RUNNER_REQUIRED_ENVIRONMENT_VALUES="${IOS_RUNNER_CANDIDATE_APP_ID_ENVIRONMENT_VALUE} NATIVE_SMOKE_EMAIL NATIVE_SMOKE_PASSWORD SENTRY_AUTH_TOKEN NATIVE_SMOKE_IOS_SENTRY_RELEASE NATIVE_SMOKE_IOS_SENTRY_DIST"
IOS_RUNNER_REQUIRED_REPOSITORY_VARIABLES="NATIVE_SMOKE_IOS_BUILD_ID"
IOS_RUNNER_REQUIRED_RELEASE_VALUES="${IOS_RUNNER_REQUIRED_ENVIRONMENT_VALUES} ${IOS_RUNNER_REQUIRED_REPOSITORY_VARIABLES}"
IOS_RUNNER_CANDIDATE_PREFLIGHT_MARKER="SENTRY_RELEASE_PREFLIGHT_PASSED_V1"

readonly IOS_RUNNER_PNPM_VERSION
readonly IOS_RUNNER_JAVA_MINIMUM_MAJOR
readonly IOS_RUNNER_SIMULATOR_NAME
readonly IOS_RUNNER_SIMULATOR_DEVICE_TYPE
readonly IOS_RUNNER_REQUIRED_COMMANDS
readonly IOS_RUNNER_CANDIDATE_APP_ID_ENVIRONMENT_VALUE
readonly IOS_RUNNER_REQUIRED_ENVIRONMENT_VALUES
readonly IOS_RUNNER_REQUIRED_REPOSITORY_VARIABLES
readonly IOS_RUNNER_REQUIRED_RELEASE_VALUES
readonly IOS_RUNNER_CANDIDATE_PREFLIGHT_MARKER